### ISSUE TITLE
import JSON fails with utf16_is_surrogate undefined

### ISSUE THREAD

**Issue by rajaths589** [JuliaLang/JSON.jl#110] opened 2015-07-01 06:54 UTC
Fails at Line 141 in Parser.jl 
on using JSON

**Comment by swt30** [comment] 2015-07-01 14:48
Introduced by https://github.com/JuliaLang/julia/pull/11551, specifically https://github.com/JuliaLang/julia/commit/a286ce0a119c4d5a96a1633a83713e2a97bbf015 which appears to have removed `utf16_is_surrogate`. In at least one place it's replaced by `is_surrogate_codeunit` (https://github.com/JuliaLang/julia/commit/a286ce0a119c4d5a96a1633a83713e2a97bbf015#diff-c77c77957abcbf5ff43edad984ad701dR48)

**Comment by IainNZ** [comment] 2015-07-01 14:52
@ScottPJones your expertise needed here

**Comment by ScottPJones** [comment] 2015-07-01 14:56
I'm adding something to deprecate.
The problem is that the JSON package is using an undocumented, unexported function,
and when I first wrote the UTF checking/conversion code, I wasn't aware that that was being done
(I now have all of the registered packages downloaded, and grep to make sure anything I change is tested/deprecated if it is used anywhere in the packages).

**Comment by IainNZ** [comment] 2015-07-01 14:59
Best solution might be to fix JSON.jl to use only documented functions, if at all possible, rather than adding a deprecation to Base.

**Comment by IainNZ** [comment] 2015-07-01 15:00
Normally PkgEval could identify all the breakages but the one thing it needs to work is JSON

**Comment by ScottPJones** [comment] 2015-07-01 15:11
Should I just submit a PR to the JSON package instead?

**Comment by IainNZ** [comment] 2015-07-01 15:18
Ideally yes. Although, it seems like here:
https://github.com/JuliaLang/JSON.jl/blob/e583641c540dcdafbbe4f748cd12cba544ce12c5/src/Parser.jl#L137-L143
It might sufficient just to back to the pre-0.3.0 definitions? Ideally though we'd use the code from Base though in some sensible way. We can drop the pre-0.3 stuff too.

**Comment by ScottPJones** [comment] 2015-07-01 16:03
They should use their own, at least until functions that are made to be public are placed in Base.

**Comment by ScottPJones** [comment] 2015-07-01 18:55
Fixed in #111

**Closed** 2015-07-01 21:28 UTC
